# Generated by Django 5.2.8 on 2025-11-18 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_eligibilityrequest_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Assigned barangay for barangay officials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='app.barangay'),
        ),
    ]
