# Generated by Django 5.2.8 on 2025-11-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userprofile_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Assigned barangay (for Barangay Officials only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='app.barangay'),
        ),
    ]
