# Generated by Django 5.2.8 on 2025-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_userprofile_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
    ]
