# Generated by Django 5.2.8 on 2025-11-27 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile_approved_at_userprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
