# Generated by Django 5.2.8 on 2025-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
