# Generated by Django 5.2.8 on 2025-12-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_userprofile_options_userprofile_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
    ]
