# Generated by Django 5.2.8 on 2025-12-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_eligibilityrequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (shown to applicant)', null=True),
        ),
    ]
