# Generated by Django 5.2.8 on 2025-12-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userprofile_approved_at_userprofile_approved_by_and_more'),
        ('app', '0030_alter_eligibilityrequest_rejection_reason'),
    ]

    operations = [
    ]
