# Generated by Django 6.0 on 2025-12-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20251206_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Assigned barangay (optional - leave empty for municipal-level users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='app.barangay'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dilg staff', 'DILG Staff'), ('field user', 'Field User')], max_length=50),
        ),
    ]
