# Generated by Django 6.0 on 2025-12-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_userprofile_barangay_alter_userprofile_role'),
    ]

    operations = [
    ]
