# Generated by Django 6.0 on 2025-12-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Assigned barangay (for Barangay Users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='app.barangay'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dilg staff', 'DILG Staff'), ('barangay user', 'Barangay User')], max_length=50),
        ),
    ]
