# Generated by Django 6.0 on 2026-01-08 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_userprofile_barangay_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsubmission',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='e.g., Jr., Sr., III', max_length=20, null=True)),
                ('position', models.CharField(help_text='e.g., Punong Barangay, Kagawad', max_length=100)),
                ('position_type', models.CharField(choices=[('elective', 'Elective'), ('appointive', 'Appointive')], default='elective', max_length=20)),
                ('term_start', models.DateField(help_text='Start date of term')),
                ('term_end', models.DateField(help_text='End date of term')),
                ('years_served', models.DecimalField(blank=True, decimal_places=1, help_text='Automatically calculated from term dates', max_digits=4, null=True)),
                ('term_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secretary', models.ForeignKey(help_text='The barangay secretary who manages this official', on_delete=django.db.models.deletion.CASCADE, related_name='barangay_officials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barangay Official',
                'verbose_name_plural': 'Barangay Officials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['secretary', 'position'], name='app_baranga_secreta_af7c15_idx'), models.Index(fields=['term_status', 'created_at'], name='app_baranga_term_st_3a16b7_idx')],
            },
        ),
    ]
