# Generated by Django 6.0 on 2026-01-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_requirementsubmission_year_barangayofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
